name: tox-pytest-Okken-2022

# Run tests every time either code is pushed to the repository or a pull request is created
on: [push, pull_request]

jobs:
  build:

    # Specify which operating system to run the tests on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Specify which Python versions to run
        python: ["3.10", "3.11", "3.12"]

    steps:
      # Check out the repository by using the latest `actions/checkout@main` GitHub tool
      # (without specifying versions like `...@v2`, `...@v3` and so on)
      # so the rest of the workflow can access it.
      - uses: actions/checkout@main
      - name: Setup Python
        # Get Python configured and installed in a build environment
        # by using the latest `setup-python@main` GitHub tool.
        uses: actions/setup-python@main
        with:
          # Create an environment for each of the Python versions listed in matrix: python
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        # Install tox
        run: pip install tox
      - name: Run Tox
        # Run tox selecting the correct version of Python specified in `tox.ini`
        run: tox -e py
